In [1]:
import pandas as pd
import random
from datetime import datetime, timedelta

In [2]:
categories = {
    "Mobile": {
        "Smartphone": [
            ("Samsung", "Galaxy A56"),
            ("Apple", "iPhone 15"),
            ("OnePlus", "Nord CE4"),
            ("Realme", "Narzo 70"),
            ("Redmi", "Note 13")
        ]
    },

    "Laptop": {
        "Gaming Laptop": [
            ("Asus", "ROG Strix"),
            ("Acer", "Nitro V"),
            ("Lenovo", "Legion 5")
        ],

        "Business Laptop": [
            ("HP", "Pavilion 14"),
            ("Dell", "Inspiron 15")
        ]
    },

    "Fashion": {
        "Shoes": [
            ("Nike", "Air Max"),
            ("Adidas", "Ultraboost"),
            ("Puma", "Runner X")
        ],

        "Jeans": [
            ("Levis", "511 Slim"),
            ("Wrangler", "Classic Fit")
        ]
    },

    "Electronics": {
        "Headphones": [
            ("Boat", "Rockerz 450"),
            ("Sony", "WH-CH520"),
            ("JBL", "Tune 760")
        ],

        "Smart Watch": [
            ("Noise", "ColorFit"),
            ("Fire-Boltt", "Ninja"),
            ("Boat", "Wave Neo")
        ]
    }
}

suppliers = [
    "Tech World Pvt Ltd",
    "Digital Hub",
    "Elite Fashion",
    "Future Retail",
    "Smart Electronics"
]

warranty = [
    "6 Months",
    "12 Months",
    "24 Months"
]

status = [
    "Active",
    "Discontinued"
]
colors = [
    "Black",
    "White",
    "Blue",
    "Red",
    "Silver",
    "Gray",
    "Green"
]

gst = [5, 12, 18, 28]

return_eligible = [
    "Yes",
    "No"
]

In [8]:
products = []

for i in range(1, 101):

    category = random.choice(list(categories.keys()))

    subcategory = random.choice(list(categories[category].keys()))

    brand, model = random.choice(categories[category][subcategory])

    product_name = brand + " " + model

    
    if category == "Mobile":
        cost_price = random.randint(8000, 60000)

    elif category == "Laptop":
        cost_price = random.randint(25000, 90000)

    elif category == "Fashion":
        cost_price = random.randint(500, 5000)

    else:
        cost_price = random.randint(800, 20000)

   
    profit = random.randint(500, 8000)

   
    selling_price = cost_price + profit

   
    discount = random.choice([5, 10, 15, 20, 25, 30, 35])

 
    stock = random.randint(10, 500)

    
    rating = round(random.uniform(3.5, 5.0), 1)

   
    supplier = random.choice(suppliers)

    
    launch_date = (
        datetime(2024, 1, 1)
        + timedelta(days=random.randint(0, 730)) #random number of days within approximately three years timedelta add those days to the starting date
    ).date()

    

    color = random.choice(colors)

    gst_value = random.choice(gst)

    return_status = random.choice(return_eligible)

   
    product = [
        f"P{i:03}",
        product_name,
        category,
        subcategory,
        brand,
        cost_price,
        selling_price,
        profit,
        discount,
        stock,
        rating,
        supplier,
        launch_date,
        random.choice(warranty),
        random.choice(status),
        color,
        gst_value,
        return_status
    ]

    products.append(product)

In [9]:
products_df = pd.DataFrame(
    products,
    columns=[
        "ProductID",
        "ProductName",
        "Category",
        "SubCategory",
        "Brand",
        "CostPrice",
        "SellingPrice",
        "Profit",
        "Discount",
        "StockQuantity",
        "Rating",
        "Supplier",
        "LaunchDate",
        "Warranty",
        "ProductStatus",
        "Color",
        "Gst",
        "ReturnEligible"
    ]
)

In [25]:
products_df.head()

,ProductID,ProductName,Category,SubCategory,Brand,CostPrice,SellingPrice,Profit,Discount,StockQuantity,Rating,Supplier,LaunchDate,Warranty,ProductStatus
0,P001,Redmi Note 13,Mobile,Smartphone,Redmi,17003,19834,2831,10,255,4.6,Smart Electronics,2024-07-16,24 Months,Active
1,P002,Noise ColorFit,Electronics,Smart Watch,Noise,20132,20918,786,35,360,3.9,Smart Electronics,2024-02-21,6 Months,Active
2,P003,HP Pavilion 14,Laptop,Business Laptop,HP,36617,39787,3170,20,490,3.8,Tech World Pvt Ltd,2025-06-20,12 Months,Discontinued
3,P004,Nike Air Max,Fashion,Shoes,Nike,35718,38065,2347,30,205,4.8,Smart Electronics,2024-10-01,24 Months,Discontinued
4,P005,JBL Tune 760,Electronics,Headphones,JBL,41552,44663,3111,35,14,3.7,Digital Hub,2024-09-26,24 Months,Discontinued

In [31]:
products_df.to_excel(
    r"C:\Users\Admin\Desktop\Retail Sale\Raw Data\Product.xlsx",
    index=False
)

In [10]:
products_df.shape

(100, 18)

In [15]:
customers=[]

In [2]:
import pandas as pd
import random
from datetime import datetime, timedelta

In [3]:

first_names = [
    "Aarav","Vivaan","Aditya","Vihaan","Arjun","Sai","Krishna","Rahul",
    "Rohan","Amit","Akash","Karan","Ankit","Yash","Harsh","Siddharth",
    "Priya","Sneha","Ananya","Aditi","Pooja","Neha","Riya","Kavya",
    "Shreya","Isha","Muskan","Nisha","Simran","Khushi","Meera","Sakshi"
]


last_names = [
    "Sharma","Patel","Verma","Gupta","Singh","Yadav","Joshi","Kulkarni",
    "Patil","Deshmukh","Pawar","Jadhav","More","Kale","Chavan","Naik",
    "Reddy","Nair","Das","Ghosh","Mishra","Pandey","Roy","Bose"
]


locations = {
    "Maharashtra": ["Pune","Mumbai","Nagpur","Nashik"],
    "Gujarat": ["Ahmedabad","Surat","Vadodara","Rajkot"],
    "Karnataka": ["Bengaluru","Mysuru","Hubli"],
    "Tamil Nadu": ["Chennai","Coimbatore","Madurai"],
    "Delhi": ["New Delhi"],
    "Uttar Pradesh": ["Lucknow","Kanpur","Noida"],
    "West Bengal": ["Kolkata","Siliguri"],
    "Rajasthan": ["Jaipur","Udaipur"]
}


region = {
    "Maharashtra":"West",
    "Gujarat":"West",
    "Karnataka":"South",
    "Tamil Nadu":"South",
    "Delhi":"North",
    "Uttar Pradesh":"North",
    "West Bengal":"East",
    "Rajasthan":"North-West"
}

occupations = {
    "Student": (0,200000),
    "Engineer": (500000,1500000),
    "Doctor": (800000,2500000),
    "Teacher": (300000,800000),
    "Business": (600000,3000000),
    "IT Professional": (500000,1800000),
    "Government Employee": (400000,1200000),
    "Homemaker": (0,100000),
    "Freelancer": (200000,1200000)
}

payment_methods = [
    "UPI",
    "Credit Card",
    "Debit Card",
    "Cash on Delivery",
    "Net Banking"
]

memberships = [
    "Silver",
    "Gold",
    "Platinum"
]

In [4]:
customers=[]

In [5]:
for i in range(1, 2001):

    customer_id = f"C{i:05}"

    first_name = random.choice(first_names)
    last_name = random.choice(last_names)

    customer_name = first_name + " " + last_name

    gender = random.choice(["Male", "Female"])

    age = random.randint(18, 60)

    state = random.choice(list(locations.keys()))

    city = random.choice(locations[state])

    customer_region = region[state]

    pincode = random.randint(100000, 999999)

    email = (
        first_name.lower() + "." +
        last_name.lower() +
        str(random.randint(100,999)) +
        "@gmail.com"
    )

    phone = str(random.randint(6000000000, 9999999999))

    join_date = (
        datetime(2023,1,1) +
        timedelta(days=random.randint(0,1095))
    ).date()

    customer_type = random.choices(
        ["Returning","New"],
        weights=[70,30]
    )[0]

    membership = random.choices(
        ["Silver","Gold","Platinum"],
        weights=[60,30,10]
    )[0]

    payment = random.choice(payment_methods)

    occupation = random.choice(list(occupations.keys()))

    income_range = occupations[occupation]

    annual_income = random.randint(
        income_range[0],
        income_range[1]
    )

    loyalty_points = random.randint(100,10000)

    customer = [

        customer_id,
        first_name,
        last_name,
        customer_name,
        gender,
        age,
        email,
        phone,
        city,
        state,
        customer_region,
        pincode,
        join_date,
        customer_type,
        membership,
        payment,
        occupation,
        annual_income,
        loyalty_points

    ]

    customers.append(customer)

In [6]:
customers_df = pd.DataFrame(
    customers,
    columns=[
        "CustomerID",
        "FirstName",
        "LastName",
        "CustomerName",
        "Gender",
        "Age",
        "Email",
        "Phone",
        "City",
        "State",
        "Region",
        "Pincode",
        "JoinDate",
        "CustomerType",
        "Membership",
        "PreferredPayment",
        "Occupation",
        "AnnualIncome",
        "LoyaltyPoints"
    ]
)

In [7]:
customers_df.head()

,CustomerID,FirstName,LastName,CustomerName,Gender,Age,Email,Phone,City,State,Region,Pincode,JoinDate,CustomerType,Membership,PreferredPayment,Occupation,AnnualIncome,LoyaltyPoints
0,C00001,Arjun,Naik,Arjun Naik,Female,53,arjun.naik968@gmail.com,7267466232,Udaipur,Rajasthan,North-West,353197,2023-10-18,Returning,Gold,Credit Card,Teacher,462766,8853
1,C00002,Vivaan,Bose,Vivaan Bose,Female,29,vivaan.bose184@gmail.com,7847268614,New Delhi,Delhi,North,769864,2024-07-27,Returning,Gold,Credit Card,Teacher,714924,6135
2,C00003,Rohan,Patel,Rohan Patel,Female,57,rohan.patel674@gmail.com,9762044425,Coimbatore,Tamil Nadu,South,811989,2023-11-29,New,Platinum,Net Banking,Freelancer,686884,303
3,C00004,Sai,Jadhav,Sai Jadhav,Male,23,sai.jadhav354@gmail.com,7272339776,Lucknow,Uttar Pradesh,North,879826,2025-01-08,Returning,Silver,Debit Card,Business,1261208,5947
4,C00005,Priya,Naik,Priya Naik,Female,27,priya.naik952@gmail.com,7374099572,Kolkata,West Bengal,East,640152,2023-09-20,Returning,Silver,UPI,Teacher,772270,4134

In [9]:
customers_df.shape

(2000, 19)

In [10]:
customers_df.to_excel(
    r"C:\Users\Admin\Desktop\Retail Sale\Raw Data\Customers.xlsx",
    index=False
)

In [1]:
import pandas as pd
import random
from datetime import datetime, timedelta

In [2]:
products_df = pd.read_excel(
    r"C:\Users\Admin\Desktop\Retail Sale\Raw Data\Product.xlsx"
)

In [3]:
customers_df = pd.read_excel(
    r"C:\Users\Admin\Desktop\Retail Sale\Raw Data\Customers.xlsx"
)

In [4]:
orders=[]

In [5]:
order_status = [
    "Delivered",
    "Cancelled",
    "Returned"
]

sales_channel = [
    "Website",
    "Mobile App"
]

delivery_type = [
    "Standard",
    "Express"
]

coupon_codes = [
    "NONE",
    "SAVE10",
    "WELCOME5",
    "FEST20",
    "NEWUSER"
]

warehouses = [
    "Pune",
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Hyderabad"
]

priorities = [
    "Low",
    "Medium",
    "High"
]

In [6]:
for i in range(1, 10001):

    order_id = f"O{i:06}"

    invoice_no = f"INV{i:06}"

    order_date = (
        datetime(2024, 1, 1) +
        timedelta(days=random.randint(0, 730))
    ).date()

    customer = customers_df.sample(1).iloc[0]

    product = products_df.sample(1).iloc[0]

    customer_id = customer["CustomerID"]

    product_id = product["ProductID"]

    quantity = random.randint(1, 5)

    unit_price = product["SellingPrice"]

    cost_price = product["CostPrice"]

    discount = random.choice([0, 5, 10, 15, 20])

    gst = product["Gst"]

    payment = customer["PreferredPayment"]

    sales_channel_value = random.choice(sales_channel)

    warehouse = random.choice(warehouses)

    delivery = random.choice(delivery_type)

    shipping_charge = random.choice([0, 49, 99, 149])

    coupon = random.choice(coupon_codes)

    status = random.choices(
        ["Delivered", "Cancelled", "Returned"],
        weights=[85, 10, 5]
    )[0]

    priority = random.choice(priorities)

    festival_sale = random.choice(["Yes", "No"])

    customer_rating = random.randint(1, 5)

    return_status = "Yes" if status == "Returned" else "No"

    sales_amount = quantity * unit_price

    discount_amount = sales_amount * discount / 100

    taxable_amount = sales_amount - discount_amount

    gst_amount = taxable_amount * gst / 100

    final_sales = taxable_amount + gst_amount

    profit = (unit_price - cost_price) * quantity

    hour = random.randint(8, 22)

    if hour < 12:
        time_of_day = "Morning"
    elif hour < 17:
        time_of_day = "Afternoon"
    else:
        time_of_day = "Evening"

    month = order_date.strftime("%B")

    quarter = f"Q{((order_date.month-1)//3)+1}"

    year = order_date.year

    salesperson = f"EMP{random.randint(1,50):03}"

    orders.append([
        order_id,
        invoice_no,
        order_date,
        customer_id,
        product_id,
        quantity,
        unit_price,
        cost_price,
        discount,
        gst,
        round(final_sales,2),
        round(profit,2),
        payment,
        status,
        coupon,
        festival_sale,
        sales_channel_value,
        warehouse,
        delivery,
        shipping_charge,
        customer_rating,
        return_status,
        priority,
        salesperson,
        time_of_day,
        month,
        quarter,
        year
    ])

In [7]:
orders_df = pd.DataFrame(
    orders,
    columns=[
        "OrderID",
        "InvoiceNo",
        "OrderDate",
        "CustomerID",
        "ProductID",
        "Quantity",
        "UnitPrice",
        "CostPrice",
        "Discount",
        "GST",
        "SalesAmount",
        "Profit",
        "PaymentMethod",
        "OrderStatus",
        "CouponCode",
        "FestivalSale",
        "SalesChannel",
        "Warehouse",
        "DeliveryType",
        "ShippingCharge",
        "CustomerRating",
        "ReturnStatus",
        "OrderPriority",
        "SalesPersonID",
        "TimeOfDay",
        "Month",
        "Quarter",
        "Year"
    ]
)

In [8]:
orders_df.shape

(10000, 28)

In [9]:
orders_df.to_excel(
    r"C:\Users\Admin\Desktop\Retail Sale\Raw Data\Orders.xlsx",
    index=False
)

In [19]:
orders_df = pd.read_excel(
    r"C:\Users\Admin\Desktop\Retail Sale\Raw Data\Orders.xlsx"
)

customers_df = pd.read_excel(
    r"C:\Users\Admin\Desktop\Retail Sale\Raw Data\Customers.xlsx"
)

In [20]:
customer_lookup = customers_df.set_index("CustomerID")

In [21]:
shipping = []

couriers = [
    "Delivery",
    "Blue Dart",
    "DTDC",
    "Ecom Express",
    "XpressBees",
    "India Post"
]

statuses = [
    "Delivered",
    "In Process",
    "Out for Delivery",
    "Delayed"
]

In [22]:
for i, order in orders_df.iterrows():

    shipping_id = f"SH{i+1:06}"

    order_id = order["OrderID"]

    customer = customer_lookup.loc[order["CustomerID"]]

    courier = random.choice(couriers)

    warehouse = order["Warehouse"]

    dispatch_date = order["OrderDate"] + timedelta(days=random.randint(1,2))

    estimated_delivery = dispatch_date + timedelta(days=random.randint(2,5))

    actual_delivery = estimated_delivery + timedelta(days=random.randint(-1,2))

    if actual_delivery <= estimated_delivery:
        shipping_status = "Delivered"
    else:
        shipping_status = random.choice(statuses)

    delivery_days = (actual_delivery - dispatch_date).days

    shipping_cost = random.choice([0,49,99,149,199])

    tracking_number = f"TRK{random.randint(100000,999999)}"

    delivery_city = customer["City"]

    delivery_state = customer["State"]

    delivery_zone = customer["Region"]

    delivery_attempt = random.randint(1,3)

    customer_received = "Yes" if shipping_status == "Delivered" else "No"

    shipping.append([
        shipping_id,
        order_id,
        courier,
        warehouse,
        dispatch_date,
        estimated_delivery,
        actual_delivery,
        shipping_status,
        delivery_days,
        shipping_cost,
        tracking_number,
        delivery_city,
        delivery_state,
        delivery_zone,
        delivery_attempt,
        customer_received
    ])

In [23]:
shipping_df = pd.DataFrame(
    shipping,
    columns=[
        "ShippingID",
        "OrderID",
        "CourierPartner",
        "Warehouse",
        "DispatchDate",
        "EstimatedDelivery",
        "ActualDelivery",
        "ShippingStatus",
        "DeliveryDays",
        "ShippingCost",
        "TrackingNumber",
        "DeliveryCity",
        "DeliveryState",
        "DeliveryZone",
        "DeliveryAttempt",
        "CustomerReceived"
    ]
)

In [24]:
shipping_df.shape

(10000, 16)

In [25]:
shipping_df.to_excel(
    r"C:\Users\Admin\Desktop\Retail Sale\Raw Data\Shipping.xlsx",
    index=False
)

In [26]:
orders_df = pd.read_excel(
    r"C:\Users\Admin\Desktop\Retail Sale\Raw Data\Orders.xlsx"
)

In [27]:
review_orders = orders_df.sample(
    n=8000,
    random_state=42
).reset_index(drop=True)

In [28]:
reviews = []

titles = [
    "Excellent Product",
    "Very Good",
    "Worth the Money",
    "Average Quality",
    "Not Satisfied",
    "Highly Recommended",
    "Good Value",
    "Amazing Product"
]

texts = [
    "Product quality is excellent.",
    "Fast delivery and good packaging.",
    "Value for money.",
    "Satisfied with the purchase.",
    "Could be better.",
    "Highly recommended.",
    "Met my expectations.",
    "Will buy again.",
    "Excellent customer service.",
    "Packaging was damaged but product is good."
]

In [29]:
for i, order in review_orders.iterrows():

    review_id = f"R{i+1:06}"

    rating = random.choices(
        [5,4,3,2,1],
        weights=[40,30,15,10,5]
    )[0]

    review_date = order["OrderDate"] + timedelta(
        days=random.randint(3,15)
    )

    recommend = "Yes" if rating >=4 else "No"

    helpful = random.randint(0,100)

    reviews.append([
        review_id,
        order["OrderID"],
        order["CustomerID"],
        order["ProductID"],
        rating,
        random.choice(titles),
        random.choice(texts),
        review_date,
        recommend,
        "Yes",
        helpful
    ])

In [30]:
reviews_df = pd.DataFrame(
    reviews,
    columns=[
        "ReviewID",
        "OrderID",
        "CustomerID",
        "ProductID",
        "Rating",
        "ReviewTitle",
        "ReviewText",
        "ReviewDate",
        "WouldRecommend",
        "VerifiedPurchase",
        "HelpfulVotes"
    ]
)

In [32]:
reviews_df.shape

(8000, 11)

In [33]:
reviews_df.to_excel(
    r"C:\Users\Admin\Desktop\Retail Sale\Raw Data\Reviews.xlsx",
    index=False
)